# Generated by Django 5.0.6 on 2024-06-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_ceac_activities',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='team_ceac_activities',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
