# Generated by Django 5.0.6 on 2024-06-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_team_ceac_activities_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_ceac_activities',
            name='completed',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team_ceac_activities',
            name='on_going',
            field=models.CharField(max_length=200),
        ),
    ]
